### ISSUE TITLE
REsolved issue where incomplete reports were being passed to pre report hooks

### ISSUE THREAD

**Issue by kolanos** [honeycombio/iopipe-plugin-honeycomb#3]
The issue where incomplete reports were being passed to pre report hooks in the Node.js and Python agents has been resolved:

* https://github.com/iopipe/iopipe-js-core/pull/233
* https://github.com/iopipe/iopipe-python/pull/135

**Comment by JamieDanielson** [comment]
This project is being sunset; please review issue #28
